### ISSUE TITLE
Log level integer should follow RFC 5424

### ISSUE THREAD

**Issue by unnawut** [ivx/ink#62]
## Current behaviour

The current mapping is https://github.com/ivx/ink/blob/master/lib/ink.ex#L241-L244:

```elixir
  defp level(level) do
    case level do
      :debug -> 20
      :info -> 30
      :warn -> 40
      :error -> 50
    end
  end
```

## Expected behaviour

The log level integer should follow The Syslog Protocol ([RFC 5424](https://tools.ietf.org/html/rfc5424)) as also [used by Erlang](http://erlang.org/documentation/doc-10.0/lib/kernel-6.0/doc/html/logger_chapter.html#log-level) and most if not all other systems.

Level | Integer | Description
-- | -- | --
emergency | 0 | system is unusable
alert | 1 | action must be taken immediately
critical | 2 | critical conditions
error | 3 | error conditions
warning | 4 | warning conditions
notice | 5 | normal but significant conditions
info | 6 | informational messages
debug | 7 | debug-level messages

**Comment by mmainz** [comment]
We use these log levels because we want to be compatible with [node-bunyan](https://github.com/trentm/node-bunyan). We have other libs in other languages that also use this standard, so we want to be compatible. I'd maybe be open to accept a slim layer of configuration for choosing Syslog log levels.
